cart/urls.py
from django.urls import path
from .import views
app_name ='cart'

urlpatterns = [
   path('add/<int:product_id>/',views.add_cart,name='add_cart'),
   path('',views.cart_detail,name="cart_detail"),
   path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
   path('fullremove/<int:product_id>/',views.full_remove,name='full_remove'),
   
   
    
    
]

onlinemarket/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('productsapp.urls')),
    path('cart/',include('cart.urls')),
    path('search_app/',include('search_app.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

productsapp/urls.py
from django.urls import path
from .import views
urlpatterns=[
    path('',views.index,name='index'),
    path('adminindex',views.adminindex,name='adminindex'),
    path('store',views.store,name='store'),
    path('addcategory',views.addcategory,name='addcategory'),
    

    path('addpro',views.addpro,name='addpro'),
    path('showproduct',views.showproduct,name='showproduct'),
    path('editdetails/<int:pk>',views.editdetails,name='editdetails'),
    path('deletedetails/<int:pk>',views.deletedetails,name='deletedetails'),
    # path('logout',views.logout,name='logout'),
    path('loginpage',views.loginpage,name='loginpage'),
    path('register',views.register,name='register'),
    path('signup',views.signup,name='signup'),
    path('login_user',views.login_user,name='login_user'),
    path('log_out',views.log_out,name='log_out'),
    path('details/<int:pk>/<int:k>/',views.details,name='details'),
    path('profile/<int:pk>',views.profile,name='profile'),
    path('showuser',views.showuser,name='showuser'),
    path('deleteuser/<int:pk>',views.deleteuser,name='deleteuser'),
    path('items',views.items,name='items'),
    path('deleteitem/<int:pk>',views.deleteitem,name='deleteitem')


]

search_app/urls.py
from django.urls import path
from .import views
app_name ='search_app'

urlpatterns = [
   path('',views.SearchResult,name="SearchResult"),
    
    
]

productsapp/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.contrib.auth.models import User


class customer(models.Model):
    # firstname = models.CharField(max_length=50)
    # lastname = models.CharField (max_length=50)
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    phone = models.CharField(max_length=10)
    address=models.CharField(max_length=100)
    # email=models.EmailField()
    # password = models.CharField(max_length=100)
    def __str__(self):
        return self.phone

class category(models.Model):
    categoryname=models.CharField(max_length=225)

    def __str__(self):
        return self.categoryname

class Brand(models.Model):
        Brand=models.CharField(max_length=255)

        def __str__(self):
            return self.Brand

    
    
class product(models.Model):
    category=models.ForeignKey(category,on_delete=models.CASCADE,blank=True,null=True)
    Brand=models.ForeignKey(Brand,on_delete=models.CASCADE,blank=True,null=True)
    image=models.ImageField(upload_to='image/',null=True,blank=True)
    name=models.CharField(max_length=25)
    description=models.CharField(max_length=255,unique=True)
    price=models.IntegerField(blank=True,null=True)
    stock=models.IntegerField(blank=True,null=True)
    # available=models.BooleanField(default=True)
    # created=models.DateTimeField(auto_now_add=True)
    # updated=models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
class Order(models.Model):
    product = models.ForeignKey(product,
                                on_delete=models.CASCADE)
    customer = models.ForeignKey(customer,
                                 on_delete=models.CASCADE)
    quantity = models.IntegerField(blank=True,null=True)
    price = models.IntegerField()
    address = models.CharField (max_length=50, default='', blank=True)
    phone = models.CharField (max_length=50, default='', blank=True)
    # date = models.DateField (default=datetime.datetime.today)
    status = models.BooleanField (default=False)
    
# class cart(models.Model):
#     product = models.ForeignKey(product,on_delete=models.CASCADE)
#     user=models.ForeignKey(User,on_delete=models.CASCADE)   
#     quantity = models.IntegerField()
#     def sub_total(self):
#         return self.product.price * self.quantity      
#     def __str__(self):
#         return self.product.name
    

productsapp/views.py
from django.shortcuts import render,redirect
from productsapp.models import product,category,customer
from django.contrib.auth.models import auth,User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from cart.models import CartItem

# Create your views here.
def index(request):
    if 'username' in request.session:
        pro=product.objects.all()
        return render(request,'index.html',{'pro':pro})
    else:
        return redirect(login_user)

def adminindex(request):
    return render(request,'adminindex.html')  

def store(request):
    return render(request,'addcategory.html')

def addcategory(request):
    if request.method=='POST':
        categoryname=request.POST['categoryname']
      
        data=category(categoryname=categoryname)
       
        
        data.save()
        return redirect('addcategory')
       
        
       
    return render(request,'addcategory.html')

  




def addpro(request):
    cat=category.objects.all()
     

    if request.method=='POST':
       
        name=request.POST['name']
        price=request.POST['price']
        description=request.POST['description']
        image=request.FILES['file'] 
        catgp=request.POST['sel']
        stock=request.POST['stock']
      
        categ=category.objects.get(id=catgp)  
        ctg= product(category=categ,image=image,name=name,description=description,price=price,stock=stock) 
        ctg.save()
        return redirect('addpro')
    return render(request,'addpro.html',{'cat':cat})
    
def showproduct(request):
    pro=product.objects.all()
    return render(request,'showproduct.html',{'pro':pro})

def editdetails(request,pk):
    pro=product.objects.get(id=pk)
    cat=category.objects.all()
    context={'pro':pro,'cat':cat}
    if request.method=='POST':
        pro.name=request.POST['name']
        pro.price=request.POST['price']
        pro.description=request.POST['description']
        pro.stock=request.POST['stock']
        if request.FILES.get('file'):
            pro.image=request.FILES.get('file')
        c=request.POST['sel']
        pro.category=category.objects.get(id=c)
        pro.save()
        return redirect('showproduct')
    return render(request,'edit.html',context)
def deletedetails(request,pk):
    std=product.objects.get(id=pk)
    std.delete()
    return redirect('showproduct')

def log_out(request):
    # if 'username' in request.session:
    #     request.session.flush()
    auth.logout(request) 
    pro=product.objects.all()
    return render(request,'index.html',{'pro':pro})

def loginpage(request):
    return render(request,'login.html') 

def register(request):
    return render(request,'register.html')

def signup(request):
    
    if 'username'in request.session:
        return redirect(index)
    if request.method=='POST':
        first_name=request.POST['first_name']
        last_name=request.POST['last_name'] 
        username=request.POST['username']  
        email=request.POST['email']
        address=request.POST['address']
        contact=request.POST['contact']
        password= request.POST['password']
        cpassword=request.POST['cpassword']
        
        if password==cpassword:
            if User.objects.filter(username=username).exists():
               messages.info(request,'this user is already exists!!!')
               return redirect('signup')
            else:
                user=User.objects.create_user(
                    first_name=first_name,
                    last_name=last_name,
                    username=username,
                    email=email,
                    password=password,
                    )
                details=customer.objects.create(
                    user=user,
                    address=address,
                    phone=contact,
                )
            user.save()    
            details.save()    
            
            return render(request,'login.html')
        else:
            messages.info(request,'password doesnot match')
            return redirect('signup')
        return redirect('loginpage')
    else:
          return render(request,'register.html')

def login_user(request):
    if request.method=='POST':
        pro=product.objects.all()
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
         # request.session["uid"]=user.id
        if user is not None:
            request.session["username"]=username
            # return redirect('index')
            if user.is_staff:
                auth.login(request,user)
                return render(request,'adminindex.html') 
            else:
                 # login(request,user)
                auth.login(request,user)
                # messages.info(request,f'Welcome {username}')
                return render(request,'index.html',{'pro':pro, 'user':user})
                # return redirect('userhomepage')
        else:
            messages.info(request,"invalid username or password")
            return redirect('loginpage') 
    else:
        return redirect(loginpage)



def details(request,pk,k):
    if 'username'in request.session:
        # return redirect(index)
        pro=product.objects.get(id=pk)
    
        return render(request,'details.html',{'product':pro, 'u':k})
    else:
       return redirect(login_user)
    
   

def profile(request,pk):
    if 'username'in request.session:
    #     return redirect(index)
        # std=User.objects.get(id=pk)
        det=customer.objects.get(user=request.user)
    
        return render(request,'profile.html',{'det':det})
    else:
       return redirect(login_user)


def showuser(request):
        # std=User.objects.filter(is_staff=0)
        det=customer.objects.all()
        return render(request,'showuser.html',{'det':det})

def deleteuser(request,pk):
    std=User.objects.get(id=pk)
    std.delete()
    return redirect('showuser')

def items(request):
    item=CartItem.objects.all()
    return render(request,'item.html',{'item':item})

def deleteitem(request,pk):
    item=CartItem.objects.get(id=pk)
    item.delete()
    return redirect('items')            


             
                    



                   

productsapp/templates/addcategory.html
{% extends 'baseadmin.html' %}
{% block body %}
<div class=" container">
    <table  align="center" >

    
        <form action="{% url 'addcategory' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                <h3 align="center">Add Categories</h3><br>
                <div class="form-group" align="center">
                   
            <input type="text" name="categoryname" placeholder="Enter Category" class="form-control w-25"><br>
          
            <input type="submit"  value="Submit" class="form-control w-25 btn btn-dark"><br>
    
       </div>
       </form>
       </table>
</div>

{% endblock %}

productsapp/templates/adminindex.html
{% extends 'baseadmin.html' %}
{% block body %}
<body >

</body>

<h1><center>Admin home page</center></h1>
<p>The administrator homepage displays a list of all accounts the user has administrator access to.</p>

{% endblock %}

productsapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %} 
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Online market</title>



    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" > 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
       
         
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">


        <!-- Font Awesome -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.css"
rel="stylesheet"
/>


    
</head>

      <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            
            Online market
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!--Navbar links-->
         
          {% if user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0  " style="left: 40%;position: absolute;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">welcome {{ user.username }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
              </li>
              <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="">All</a>
                  <a class="dropdown-item" href="">category</a>
                </div>
              </li> -->




              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'profile' user.id  %}">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active fa fa-shopping-cart" aria-current="page" href="{% url 'cart:cart_detail'  %}">Cart</a>
              </li>

              
              <form class="d-flex" role="search" action="{% url 'search_app:SearchResult' %}",method="get">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
                <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
              </form>





              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'log_out' %}">Log Out</a>
              </li>
            </ul>
          </div>
          {% else %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="left: 40%;position: absolute;">
             
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
              </li>
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'loginpage' %}">Log In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'signup' %}">Sign Up</a>
              </li>
            </ul>
          </div>
          {% endif %}

        </div>
      </nav>

      <body  style="background-color: url('https://wallpaperboat.com/wp-content/uploads/2020/12/02/62556/light-color-12.jpg')"> 
        
      <div style="min-height:80vh;">
        {% block body %}
        
        {% endblock %}
      </div>
      <div>
        {% block content %}
        
        {% endblock %}
      </div>
      
        
        <footer class="bg-light text-center text-white ">
          <!-- Grid container -->
          <div class="container p-4 pb-0">
            <!-- Section: Social media -->
            <section class="mb-4">
              <!-- Facebook -->
              <a
                class="btn text-white btn-floating m-1"
                style="background-color: #3b5998;"
                href="#!"
                role="button"
                ><i class="fab fa-facebook-f"></i
              ></a>
        
              <!-- Twitter -->
              <a
                class="btn text-white btn-floating m-1"
                style="background-color: #55acee;"
                href="#!"
                role="button"
                ><i class="fab fa-twitter"></i
              ></a>
        
              <!-- Google -->
              <a
                class="btn text-white btn-floating m-1"
                style="background-color: #dd4b39;"
                href="#!"
                role="button"
                ><i class="fab fa-google"></i
              ></a>
        
              <!-- Instagram -->
              <a
                class="btn text-white btn-floating m-1"
                style="background-color: #ac2bac;"
                href="#!"
                role="button"
                ><i class="fab fa-instagram"></i
              ></a>
        
              <!-- Linkedin -->
              <a
                class="btn text-white btn-floating m-1"
                style="background-color: #0082ca;"
                href="#!"
                role="button"
                ><i class="fab fa-linkedin-in"></i
              ></a>
              <!-- Github -->
              <a
                class="btn text-white btn-floating m-1"
                style="background-color: #333333;"
                href="#!"
                role="button"
                ><i class="fab fa-github"></i
              ></a>
            </section>
            <!-- Section: Social media -->
          </div>
          <!-- Grid container -->
        
          <!-- Copyright -->
          <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2020 Copyright:
            <a class="text-white" href="#">OnlineMarket.com</a>
          </div>
          <!-- Copyright -->
        </footer>  
        
        
        <!-- MDB -->
<script
type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.js"
></script>
 <script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script> 





<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>












      

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

productsapp/templates/cartnew.html
{% extends 'base.html' %}
{% load  static  %}

{% comment %} {% block body %} {% endcomment %}



{% comment %}{% for i in cart_items %}

<p>{{i.product.name }}</p>

{% endfor %}

 {% endcomment %}


 {% block body %}

{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart is empty </h1>
        <br>
        <p class="text-center">Please select Product <a href="{% url 'index' %}">Here</a>to continue shopping.

        </p>



    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart</h1>
        <br>
         </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                   <th colspan="5">

                    your items
                   </th>
                </tr>
              </thead>
              <tbody>

            {% for cart_item in cart_items %}
            <tr>
                <td>
               <a href="cart_item.product.get_absolute_url"><img src="{{ cart_item.product.image.url}}" width='100px' height='150px'  alt="" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-lef">
                    {{ cart_item.product.name  }}
                    <br>
                    sku:{{ cart_item.product.id}}
                    <br>
                    Price:$ {{ cart_item.product.price }}
                    <br>
                    Qty:{{ cart_item.quantity }} x $ {{ cart_item.product.price }}. {{ cart_item }}
                 </td>
                 
                 <td>
                        $ {{ cart_item.sub_total }}

                 </td>
                 {% if cart_item.quantity < cart_item.product.stock %}
                 <td>
                    
                      <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-plus"></i></a>&nbsp;
                      &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a> 
                      &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-sharp fa-solid fa-trash"></i></a> 
                 </td>
                 {% else %}
                 <td>
                  
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a> 
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash-o custom_icon"></i></i></a> 
               </td>
               {% endif %}



            </tr>
            {% endfor %}
            </tbody>    
        </table>
    </div>

<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
            <tr>
                <th>Checkout</th>



            </tr>
        </div>
   
</thead>
<tbody>
    <tr>
        <td>please review your cartitems before proceeding the payment</td>

    </tr>
    <tr>
        <td class="text-left">Your total is = <strong>{{ total }}</strong> </td>

    </tr>
    </tbody>
</table>
<div class="mx-auto">
    <a href="{% url 'index' %}" class="btn btn-secondary btn-block my_custom_button">Continue to shopping</a>


</div>
<div class="mx-auto">
    <a href="#"<button type="button" class="btn btn-success my_button">Make Payment</button></a>


</div>

</div>
</div>
</div>

{% endif %}

{% endblock %} 

productsapp/templates/details.html
{% extends 'base.html' %}
{% block body %}

<div class="container" style="background-color:white; margin-left:380px;width:560px;">
    
    <img src={{product.image.url}} style="height: 320px;margin-left:150px;">
    <div style="margin-left:180px;">
    <h5> {{product.name}}</h5>
    <h5>${{product.price}}</h5>
    <h5>{{product.description}}</h5>
    {% if product.stock <= 0 %}
    <p><b>out of stock</b></p>
    {% else %}
    <a class="btn btn-primary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
    {% endif %}




    {% comment %} <a href="{% url 'cart:add_cart' product.id  %}" class="btn btn-primary">Add to cart</a> {% endcomment %}
</div>
    </div>
{% endblock %}

productsapp/templates/item.html
{% extends 'baseadmin.html' %}
{% block body %}

<table align="center" border="1" class="table text-center " style="width:100px; ">
    <h2 align="center">Show items</h2>
    <tr>
        <th>Customer Name</th>
        <th>Image</th>
        <th>Ordered items</th>
        <th>Price</th>
        <th>Description</th>
        
        
        
        <th>Action</th>
    </tr>
    {% for p in item %}
   <tr>
       <td>{{p.user.first_name}}</td>
    <td><img width="70px" src='{{ p.product.image.url }}'></td>  
       <td>{{p.product.name}}</td>
       <td>{{p.product.price}}</td>
       <td>{{p.product.description}}</td>
       
       <td>
        <a href="{% url 'deleteitem' p.id %}"class="btn btn-danger" >Delete</a></td>
        
    </tr>
    {% endfor %}
</table>



{% endblock %}

productsapp/templates/search.html
{% extends 'base.html' %}
{% load  static  %}

{% block metadescription %}

  we have variety of products

{% endblock %}

{% block title %}
search

{% endblock %}

{% block body %}
<div>
<p class="text center my_search_text">You have searched for :<b> "{{query}}"</p>
</div>
<div class="container">
  <div class="row mx_auto">

{% for product in products %}
<div class="my_bottom_margin col-9 col-sm-12  col-md-4 col-lg-4">
  <div class="card text-center" style="min-width:18rem;">
      <a href="{{ product.get_url }}" ><img class="card-img-top " src="{{ product.image.url }}"width="30px" height="250px"  alt="{{ product.name }}"></a>

      <div class="card-body">
          <h4>{{ product.name }}</h4>
          <p>${{ product.price }}</p>
          <p>{{ product.description }}</p>
          <a href="{% url 'cart:add_cart' product.id  %}" class="btn btn-primary">Add to cart</a>

      </div>

  </div>
</div>
{% empty %}
<div class="row mx-auto">
  <p class="text-center my_search_text">0 results found </p>

</div>
{% endfor %}
</div>
</div>
{% endblock %}